# Generated by Django 5.0.2 on 2024-04-06 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BPostData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thread', models.IntegerField()),
                ('name', models.CharField(default='Anonymous', max_length=200)),
                ('text', models.CharField(max_length=500, null=True)),
                ('image', models.ImageField(null=True, upload_to='images')),
            ],
        ),
    ]
