# Generated by Django 5.0.2 on 2024-04-06 03:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bpostdata',
            name='image',
            field=models.ImageField(blank=True, default=django.utils.timezone.now, upload_to='images'),
            preserve_default=False,
        ),
    ]
