# Generated by Django 5.0.2 on 2024-04-06 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0003_bpostdata_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bpostdata',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
