# Generated by Django 5.0.2 on 2024-04-06 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0004_alter_bpostdata_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bpostdata',
            name='text',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
