# Generated by Django 5.0.2 on 2024-04-17 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0005_alter_bpostdata_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bpostdata',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bpostdata',
            name='thread',
            field=models.IntegerField(default=models.BigAutoField(primary_key=True, serialize=False)),
        ),
    ]
