# Generated by Django 5.0.2 on 2024-04-17 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0006_alter_bpostdata_id_alter_bpostdata_thread'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bpostdata',
            name='thread',
            field=models.IntegerField(default='<django.db.models.fields.BigAutoField>'),
        ),
    ]
