# Generated by Django 5.0.2 on 2024-04-17 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0007_alter_bpostdata_thread'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bpostdata',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bpostdata',
            name='thread',
            field=models.IntegerField(default=models.IntegerField(primary_key=True, serialize=False)),
        ),
    ]
