# Generated by Django 5.0.2 on 2024-04-18 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0008_alter_bpostdata_id_alter_bpostdata_thread'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bpostdata',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='bpostdata',
            name='thread',
            field=models.IntegerField(null=True),
        ),
    ]
